//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RUN.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zakaz
    {
        public int IdZakaz { get; set; }
        public int IdUsluga { get; set; }
        public int IdStatus { get; set; }
        public string DescriprionByClient { get; set; }
        public string AcceptedByWhom { get; set; }
        public Nullable<int> IdClient { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Status Status { get; set; }
        public virtual Usluga Usluga { get; set; }
    }
}
